INSERT INTO fmzcqrspersistence.dummy_database_entity (name, flag, number)
VALUES ('John', TRUE, 1000),
       ('Jane', FALSE, 2000),
       ('John', FALSE, 2500),
       ('Joanna', FALSE, 1000),
       ('John', FALSE, 2000),
       ('John', FALSE, NULL),
       ('Joanna', FALSE, NULL),
       ('Joanna', FALSE, NULL),
       ('Jane', FALSE, NULL),
       ('Jane', FALSE, 1000),
       ('Filip', FALSE, 1000),
       ('Mikolaj', FALSE, 1000),
       ('Gabriel', FALSE, 1000),
       ('Andrzej', FALSE, 1000),
       ('Zbigniew', FALSE, 1000),
       ('Bogdan', FALSE, 1000),
       ('Bartek', FALSE, 1000);